/*
 * Copyright (C) 2010-2011 Project StarGate
 */

enum sData
{
    DATA_HALFUS,
    DATA_THERALION_AND_VALIONA,
    DATA_ASCENDANT_COUNCIL,
    DATA_CHOGALL,
    DATA_SINESTRA,
    MAX_ENCOUNTER,
    // Halfus minion's
    DATA_STORM_RIDER,
    DATA_THE_TIME_WARDEN,
    DATA_THE_SLATE_DRAGON,
    DATA_NETHER_SCION,
    DATA_ORPHANED_EMERALD_WHELP,
    DATA_RESET_DRAGON
};

enum sCreature
{
    NPC_STORM_RIDER            = 44650,
    NPC_THE_TIME_WARDEN        = 44797,
    NPC_THE_SLATE_DRAGON       = 44652,
    NPC_NETHER_SCION           = 44645,
    NPC_ORPHANED_EMERALD_WHELP = 44641,
};